/* eslint-disable */
/**
 * Generated by convex codegen.
 * Stub file — will be replaced by `npx convex dev` once the project is deployed.
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as sandboxes from "../sandboxes.js";
import type * as betting from "../betting.js";
import type * as credits from "../credits.js";
import type * as events from "../events.js";
import type * as prompts from "../prompts.js";
import type * as users from "../users.js";
import type * as emails from "../emails.js";
import type * as payments from "../payments.js";
import type * as browserUse from "../browserUse.js";

declare const fullApi: ApiFromModules<{
  sandboxes: typeof sandboxes;
  betting: typeof betting;
  credits: typeof credits;
  events: typeof events;
  prompts: typeof prompts;
  users: typeof users;
  emails: typeof emails;
  payments: typeof payments;
  browserUse: typeof browserUse;
}>;

export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
export declare const components: any;
