/* eslint-disable */
/**
 * Generated by convex codegen.
 * Stub file — will be replaced by `npx convex dev` once the project is deployed.
 */

import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
export const components = {};
