/* eslint-disable */
/**
 * Generated by convex codegen.
 * Stub file — will be replaced by `npx convex dev`.
 */

import type { GenericId } from "convex/values";

export type Id<TableName extends string> = GenericId<TableName>;
